# Generated by Django 2.0.6 on 2019-10-19 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myUser', '0005_auto_20191007_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('email', models.EmailField(default='', max_length=255, primary_key=True, serialize=False)),
                ('gender', models.CharField(default='', max_length=255, null=True)),
                ('qualification', models.CharField(default='', max_length=255, null=True)),
                ('subject', models.CharField(default='', max_length=255, null=True)),
                ('password', models.CharField(default='', max_length=255, null=True)),
                ('dob', models.CharField(default='', max_length=255, null=True)),
                ('doj', models.CharField(default='', max_length=255, null=True)),
                ('dol', models.CharField(default='', max_length=255, null=True)),
                ('address', models.CharField(default='', max_length=255, null=True)),
                ('mobile', models.CharField(default='', max_length=255, null=True)),
                ('status', models.NullBooleanField(default=True)),
                ('session', models.CharField(default='', max_length=255, null=True)),
                ('image', models.CharField(default='', max_length=255, null=True)),
                ('last_login_time', models.CharField(default='', max_length=255, null=True)),
                ('last_login_date', models.CharField(default='', max_length=255, null=True)),
                ('last_logout', models.CharField(default='', max_length=255, null=True)),
                ('otp', models.CharField(default='', max_length=255, null=True)),
                ('otp_date_time', models.CharField(default='', max_length=255, null=True)),
                ('verify_link', models.CharField(default='', max_length=255, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myUser.UserRole')),
            ],
        ),
    ]
