# Generated by Django 2.0.6 on 2019-11-18 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_section_class_id'),
        ('teacher', '0003_remove_timetable_table_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(default='', max_length=255, null=True)),
                ('Attendance', models.CharField(default='', max_length=255, null=True)),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student_class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
