# Generated by Django 2.0.6 on 2019-11-11 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myUser', '0006_loginrecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('email', models.EmailField(default='', max_length=255, null=True)),
                ('gender', models.CharField(default='', max_length=255, null=True)),
                ('admission_year', models.CharField(default='', max_length=255, null=True)),
                ('admission_class', models.CharField(default='', max_length=255, null=True)),
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=255, null=True)),
                ('dob', models.CharField(default='', max_length=255, null=True)),
                ('address', models.CharField(default='', max_length=255, null=True)),
                ('mobile', models.CharField(default='', max_length=255, null=True)),
                ('status', models.NullBooleanField(default=True)),
                ('image', models.CharField(default='', max_length=255, null=True)),
                ('last_login_time', models.CharField(default='', max_length=255, null=True)),
                ('last_login_date', models.CharField(default='', max_length=255, null=True)),
                ('last_logout', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(default='', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student_class'),
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myUser.UserRole'),
        ),
    ]
