# Generated by Django 2.0.6 on 2019-11-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
