# Generated by Django 2.0.6 on 2019-11-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_section_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='class_id',
        ),
    ]
