# Generated by Django 2.0.6 on 2019-11-12 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myUser', '0006_loginrecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('email', models.EmailField(default='', max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=255, null=True)),
                ('address', models.CharField(default='', max_length=255, null=True)),
                ('mobile', models.CharField(default='', max_length=255, null=True)),
                ('is_active', models.NullBooleanField(default=True)),
                ('image', models.CharField(default='', max_length=255, null=True)),
                ('last_login_time', models.CharField(default='', max_length=255, null=True)),
                ('last_login_date', models.CharField(default='', max_length=255, null=True)),
                ('last_logout', models.CharField(default='', max_length=255, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myUser.UserRole')),
            ],
        ),
    ]
