# Generated by Django 2.0.6 on 2019-11-12 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_section_class_id'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
            preserve_default=False,
        ),
    ]
