# Generated by Django 2.0.6 on 2019-10-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0002_usersignp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSignp',
            new_name='UserSignup',
        ),
    ]
