# Generated by Django 2.0.6 on 2019-10-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0003_auto_20191003_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='confirmationLink',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='otpTime',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='userOTP',
            field=models.CharField(default='', max_length=200),
        ),
    ]
