# Generated by Django 2.0.6 on 2019-10-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0005_auto_20191007_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loginTime', models.CharField(default='', max_length=255, null=True)),
                ('logoutTime', models.CharField(default='', max_length=255, null=True)),
                ('userEmail', models.CharField(default='', max_length=255, null=True)),
                ('ipAddress', models.CharField(default='', max_length=255, null=True)),
                ('macAddress', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
    ]
