# Generated by Django 2.0.6 on 2019-11-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principle',
            name='status',
            field=models.NullBooleanField(default=True),
        ),
    ]
